# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins:
- pulp-certguard
all: false
black: true
bootstrap: false
check_commit_message: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docs: false
docs_test: true
plugin_app_label: file
plugin_camel: PulpFile
plugin_camel_short: File
plugin_caps: PULP_FILE
plugin_caps_short: FILE
plugin_dash: pulp-file
plugin_dash_short: file
plugin_name: pulp_file
plugin_snake: pulp_file
plugin_snake_short: file
pulp_settings:
pydocstyle: true
pypi_username: pulp
test: false
test_bindings: true
test_performance: true
travis_notifications:
  irc:
    channels:
    - chat.freenode.net#pulp-build
    on_failure: always
    on_success: change

